version: "3"

services:
  postgre:
    image: postgres:15.1-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: stsoft
    volumes:
      - ./pgdata:/var/lib/postgresql

  server:
    build: .
    image: python:3.10.11-alpine3.18
    restart: always

    depends_on:
      - postgre

    ports:
      - "8000:8000"
    environment: 
      - DB_PORT=5432
      - DB_HOST=postgre
