"""Added data

Revision ID: d609c58855d7
Revises: 718bcd5cfff0
Create Date: 2024-06-12 15:33:48.801583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd609c58855d7'
down_revision: Union[str, None] = '718bcd5cfff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_interval')
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tasks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('activity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['users.id'], name='tasks_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('fullanme', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('time_interval',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_owner', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='time_interval_task_id_fkey'),
    sa.ForeignKeyConstraint(['task_owner'], ['users.id'], name='time_interval_task_owner_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_interval_pkey')
    )
    # ### end Alembic commands ###
